window_width = 800
window_height = 600

OWN_MESSAGE = 0
OTHER_MESSAGE = 1

ACCEPT = 0
ACCOUNT_ALREADY_EXIST = 1
ACCOUNT_NOT_FOUND = 2
INCORRECT_PASSWORD = 3
CHAT_ALREADY_EXISTS = 4

CLOSE_CODE = 10